subnet           = "default"
image_project    = "windows-cloud"
windows_vm_image = "windows-server-2019-dc-core-v20220210"
vm_size          = "n1-standard-2"
region           = "us-central1"
db_name          = "yourdb"